### ISSUE TITLE
Título do projeto/componente

### ISSUE THREAD

**Issue by lurique** [pagarme/react-cards-component#7]
A ideia principal do componente não bate com o seu título. O termo _**Card(s)**_ é referente a cartões/cartas e o mesmo pode ser referente a cartas de jogo, tarô, correio, etc.

A sugestão é alterar o termo _**cards**_ para _**Payment Cards**_ ou até mesmo _**Credit Cards**_ (se o projeto final for referente somente a isso). Essas considerações são baseadas em questões de pesquisa, já que, por relevância, os primeiros resultados apresentados serão justamente os citados acima (cartas de jogo, tarô, correio, etc).

**Comment by thiagommedeiros** [comment]
@lurique Vc tem total razão! Inclusive estávamos discutindo isso no Slack do Pagar.me, acabei de mandar o link dessa issue lá, vamos discutir isso aqui.

Valeu pela colaboração!!

**Comment by thiagommedeiros** [comment]
Eu gosto da ideia de `react-payment-card-component`, mas será que não é um nome mto grande?

O que vcs acham? @lurique @augusto-jm-amaral

**Comment by augusto-jm-amaral** [comment]
Conforme o @grvcoelho disse, **Credit Cards** refere a cartões de crédito, podem conter cartões de débito também, eu fico com  `react-payment-card-component` :+1:

**Comment by lurique** [comment]
@thiagommedeiros, também fico com `react-payment-card-component`.

**Comment by grvcoelho** [comment]
Nice! Concordo :)

**Comment by thiagommedeiros** [comment]
Fechou, vou criar uma Issue para alterar o nome do projeto para `react-payment-card-component`.

Valeu galera!!
